media: docs/files

content:
  - name: presentation
    label: Presentation
    type: file
    path: docs/_includes/content
    filename: "presentation.md"
    fields:
      - { name: body, label: Body, type: rich-text }