services:
  jekyll:
    image: jekyll/jekyll:4.0
    # command: jekyll serve --watch --force_polling --verbose
    command: sh -c "bundle install && jekyll serve --watch --force_polling --verbose"
    ports:
      - 4000:4000
    volumes:
      - ./docs:/srv/jekyll
